version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    assignees:
      - sebbo2002
    commit-message:
      prefix: "ci"
      include: scope
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    assignees:
      - sebbo2002
    commit-message:
      prefix: "build"
      include: scope
    schedule:
      interval: weekly

