stages:
  - prepare
  - test
  - publish


prepare:
  stage: prepare
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - yarn install
    - tar -czf "node_modules.tar.gz" ./node_modules
  artifacts:
    paths:
      - node_modules.tar.gz
    expire_in: 7 day


node_6:
  image: node:6
  services:
    - docker:dind
  stage: test
  tags:
    - matt.sebbo.net
    - docker
  except:
    - tags
  script:
    - tar -xzf "node_modules.tar.gz" -C .
    - rm -f ./node_modules.tar.gz
    - npm install -g grunt-cli
    - npm install
    - npm run all

node_7:
  image: node:7
  services:
    - docker:dind
  stage: test
  tags:
    - matt.sebbo.net
    - docker
  except:
    - tags
  script:
    - tar -xzf "node_modules.tar.gz" -C .
    - rm -f ./node_modules.tar.gz
    - npm install -g grunt-cli
    - npm install
    - npm run all

node_8:
  image: node:8
  services:
    - docker:dind
  stage: test
  tags:
    - matt.sebbo.net
    - docker
  except:
    - tags
  script:
    - tar -xzf "node_modules.tar.gz" -C .
    - rm -f ./node_modules.tar.gz
    - npm install -g grunt-cli
    - npm install
    - npm run all

node_9:
  image: node:9
  services:
    - docker:dind
  stage: test
  tags:
    - matt.sebbo.net
    - docker
  except:
    - tags
  script:
    - tar -xzf "node_modules.tar.gz" -C .
    - rm -f ./node_modules.tar.gz
    - npm install -g grunt-cli
    - npm install
    - npm run all

node_10:
  image: node:10
  services:
    - docker:dind
  stage: test
  tags:
    - matt.sebbo.net
    - docker
  except:
    - tags
  script:
    - tar -xzf "node_modules.tar.gz" -C .
    - rm -f ./node_modules.tar.gz
    - npm install -g grunt-cli
    - npm install
    - npm run all


publish-test-report:
  stage: test
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - tar -xzf "node_modules.tar.gz" -C .
    - rm -f ./node_modules.tar.gz
    - npm run test
    - rm -rf /var/docker/static/ical-generator/test/*
    - mv ./test-result/test/* /var/docker/static/ical-generator/test/
  only:
    - develop

publish-coverage-report:
  stage: test
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - tar -xzf "node_modules.tar.gz" -C .
    - rm -f ./node_modules.tar.gz
    - npm run coverage
    - rm -rf /var/docker/static/ical-generator/coverage/*
    - mv ./test-result/coverage/* /var/docker/static/ical-generator/coverage/
  only:
    - develop

publish-plato-report:
  stage: test
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - tar -xzf "node_modules.tar.gz" -C .
    - rm -f ./node_modules.tar.gz
    - npm run visualize
    - rm -rf /var/docker/static/ical-generator/plato/*
    - mv ./code-visualization/* /var/docker/static/ical-generator/plato/
  only:
    - develop


sync_github:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - git reset --hard
    - git checkout $CI_COMMIT_REF_NAME
    - git pull
    - git push --force "https://${GITHUB_AUTH}@github.com/sebbo2002/ical-generator.git" --all
    - git push --force "https://${GITHUB_AUTH}@github.com/sebbo2002/ical-generator.git" --tags
  only:
    - develop
    - master


publish_npm:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - tar -xzf "node_modules.tar.gz" -C .
    - rm -f ./node_modules.tar.gz
    - npm run build
    - npm run bump
    - npm publish
  only:
    - tags
