stages:
  - test
  - publish

node_6:
  image: node:6
  services:
    - docker:dind
  stage: test
  tags:
    - matt.sebbo.net
    - docker
  script:
    - npm install -g grunt-cli
    - npm install
    - npm test

node_7:
  image: node:7
  services:
    - docker:dind
  stage: test
  tags:
    - matt.sebbo.net
    - docker
  script:
    - npm install -g grunt-cli
    - npm install
    - npm test

node_8:
  image: node:8
  services:
    - docker:dind
  stage: test
  tags:
    - matt.sebbo.net
    - docker
  script:
    - npm install -g grunt-cli
    - npm install
    - npm test

node_9:
  image: node:9
  services:
    - docker:dind
  stage: test
  tags:
    - matt.sebbo.net
    - docker
  script:
    - npm install -g grunt-cli
    - npm install
    - npm test

node_10:
  image: node:10
  services:
    - docker:dind
  stage: test
  tags:
    - matt.sebbo.net
    - docker
  script:
    - npm install -g grunt-cli
    - npm install
    - npm test

publish_github:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - git pull
    - git push --force "https://${GITHUB_AUTH}@github.com/sebbo2002/ical-generator.git" --all
    - git push --force "https://${GITHUB_AUTH}@github.com/sebbo2002/ical-generator.git" --tags
  only:
    - develop

publish_plato:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - yarn install
    - npm run visualize
    - rm -rf /var/docker/static/ical-generator/plato/*
    - mv ./code-visualization/* /var/docker/static/ical-generator/plato/
  only:
    - develop

publish_npm_next:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - yarn install
    - npm run bump:develop
    - npm run build
    - echo $(cat ./package.json | jq '.version' -rce)
    - npm publish --tag "next"
  only:
    - develop

publish_npm:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - yarn install
    - npm run bump:production
    - npm run build
    - echo $(cat ./package.json | jq '.version' -rce)
    - npm publish
  only:
    - master
