name: is-semantic-pr
on:
  pull_request: null

jobs:
  is-semantic-release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'depfu/batch_dev/') != true }}
    steps:
      - name: ðŸ¤– is-semantic-release
        uses: sebbo2002/action-is-semantic-pr@v1.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
