name: ReleaseBot

on:
  workflow_dispatch:
  push:
    branches: ['develop']
  schedule:
    - cron: '25 8 * * 3'

jobs:
  release-bot:
    runs-on: ubuntu-latest
    steps:
      - name: â˜ï¸ Checkout Project
        uses: actions/checkout@v2
      - name: â˜ï¸ Checkout ReleaseBot
        uses: actions/checkout@v2
        with:
          repository: sebbo2002/release-bot
          path: ./.actions/release-bot
      - name: ğŸ“¦ Install Dependencies
        run: npm ci
        working-directory: ./.actions/release-bot
      - name: ğŸ¤– Run ReleaseBot
        uses: ./.actions/release-bot
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
