name: ReleaseBot

on:
  workflow_dispatch:
  push:
    branches: ['develop']
  schedule:
    - cron: '25 8 * * 3'

jobs:
  release-bot:
    runs-on: ubuntu-latest
    steps:
      - name: ‚òÅÔ∏è Checkout Project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: ‚òÅÔ∏è Checkout ReleaseBot
        uses: actions/checkout@v2
        with:
          repository: sebbo2002/release-bot
          path: ./.actions/release-bot
      - name: üì¶ Install Dependencies
        run: npm ci
        working-directory: ./.actions/release-bot
      - name: ü§ñ Run ReleaseBot
        uses: ./.actions/release-bot
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
