name: ReleaseBot
on:
  workflow_dispatch:
  push:
    branches: ['develop']
  schedule:
    - cron: '30 8 * * 3'

jobs:
  release-bot:
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'sebbo2002/js-template' }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: â˜ï¸ Checkout Project
        uses: actions/checkout@v3
      - name: â˜ï¸ Checkout ReleaseBot
        uses: actions/checkout@v3
        with:
          repository: sebbo2002/release-bot
          path: ./.actions/release-bot
      - name: ğŸ”§ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - name: ğŸ“¦ Install Dependencies
        run: npm ci
        working-directory: ./.actions/release-bot
      - name: ğŸ¤– Run ReleaseBot
        uses: ./.actions/release-bot
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
