name: Cleanup issues and PRs
on:
  schedule:
    - cron: '0 10 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: ðŸ§¹ Cleanup issues & pull requests
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity :sleeping:
            It will be closed in 14 days if no further activity occurs. To unstale this issue, add a comment with detailed explanation.
            Thank you for your contributions :heart:
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had recent activity :sleeping:
            It will be closed in 14 days if no further activity occurs. To unstale this pull request, add a comment with detailed explanation.
            Thank you for your contributions :heart:
          days-before-stale: 60
          days-before-close: 14
          stale-issue-label: stale
          stale-pr-label: stale
